# Generated by Django 3.0.5 on 2021-12-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('last_sale', models.TextField()),
                ('net_change', models.TextField()),
                ('p_change', models.TextField()),
                ('market_cap', models.TextField()),
                ('country', models.TextField()),
                ('ipo_year', models.TextField()),
                ('volume', models.TextField()),
                ('sector', models.TextField()),
                ('industry', models.TextField()),
            ],
        ),
    ]
